# Generated by Django 3.2.8 on 2021-10-14 02:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("SPOTIFY", "Spotify"), ("YOUTUBE", "Youtube")],
                        max_length=20,
                        verbose_name="platform",
                    ),
                ),
                ("metadata", models.JSONField(verbose_name="metadata")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
